copy d:\simutgw_slu\Simutgw_SolutionPack\编程风格习惯.txt e:\ProgramWorkstation\SystemGtest /y
copy d:\simutgw_slu\Simutgw_SolutionPack\错误记录.txt e:\ProgramWorkstation\SystemGtest /y
copy d:\simutgw_slu\Simutgw_SolutionPack\SystemGtest\*.cpp  e:\ProgramWorkstation\SystemGtest /y
xcopy d:\simutgw_slu\Simutgw_SolutionPack\SystemGtest\AShareCheckOrder e:\ProgramWorkstation\SystemGtest\AShareCheckOrder /y
xcopy d:\simutgw_slu\Simutgw_SolutionPack\SystemGtest\Gtests  e:\ProgramWorkstation\SystemGtest\Gtests /y
xcpoy d:\simutgw_slu\Simutgw_SolutionPack\SystemGtest\MatchMode e:\ProgramWorkstation\SystemGtest\MatchMode /y
xcopy d:\simutgw_slu\Simutgw_SolutionPack\SystemGtest\SHShare e:\ProgramWorkstation\SystemGtest\SHShare /y
xcopy d:\simutgw_slu\Simutgw_SolutionPack\SystemGtest\StockAsset e:\ProgramWorkstation\SystemGtest\StockAsset /y
xcopy d:\simutgw_slu\Simutgw_SolutionPack\SystemGtest\SystemGtestConfigs e:\ProgramWorkstation\SystemGtest\SystemGtestConfigs /y
